### ISSUE TITLE
Plugin does not exist, but it is installed already

### ISSUE THREAD

**Issue by zhaoxiaomin1983** [adnovum/sonar-build-breaker#36]
I use sonarqube in gitlab-runner. And this build breaker plugin worked well before. But recently occasionally this error happened when publish the result to sonarqube. 
sonarqube: Version 6.7.1
build breaker: 2.2

Error Details
java.lang.IllegalArgumentException: Plugin [buildbreaker] does not exist
	at org.sonar.ce.container.CePluginRepository.getPluginInfo(CePluginRepository.java:95)
	at org.sonar.server.computation.task.projectanalysis.step.LoadReportAnalysisMetadataHolderStep.getBasePluginKey(LoadReportAnalysisMetadataHolderStep.java:132)
	at org.sonar.server.computation.task.projectanalysis.step.LoadReportAnalysisMetadataHolderStep.lambda$loadQualityProfiles$1(LoadReportAnalysisMetadataHolderStep.java:127)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.sonar.server.computation.task.projectanalysis.step.LoadReportAnalysisMetadataHolderStep.loadQualityProfiles(LoadReportAnalysisMetadataHolderStep.java:125)
	at org.sonar.server.computation.task.projectanalysis.step.LoadReportAnalysisMetadataHolderStep.execute(LoadReportAnalysisMetadataHolderStep.java:88)
	at org.sonar.server.computation.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:64)
	at org.sonar.server.computation.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:52)
	at org.sonar.server.computation.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:73)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.executeTask(CeWorkerImpl.java:134)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:97)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.withCustomizedThreadName(CeWorkerImpl.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:73)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zhaoxiaomin1983** [comment]
Emergency for this issue. Please help check it. Thanks!

**Comment by dbmeneses** [comment]
Did you uninstall the plugin at some point? The problem looks like this one: https://jira.sonarsource.com/browse/SONAR-10315

**Comment by zhaoxiaomin1983** [comment]
No,I don’t uninstall it.I can find it in the plugin folder. I use sonarqube ce version. I cannot find build breaker plugin in the ui.So I download it from website, then put it in the plugin folder.  I have no idea for this. If the plugin is not exist, all will be failed. But now it happened sometimes, not always.

**Comment by sandro-h** [comment]
Hey @zhaoxiaomin1983, late answer (we've since taken over maintainership of the plugin).  In the meantime SonarQube is at version 7.9, and we've also just released a new version of the sonar-build-breaker which supports it. I suggest to upgrade your SonarQube version if you haven't already in the meantime. I'll close this issue since it's quite old, but if you still encounter the same problems, feel free to let me know.
