### ISSUE TITLE
Support for SonerQube 7?

### ISSUE THREAD

**Issue by christophwin** [adnovum/sonar-build-breaker#42]
Hello,
do you plan support for newer sonarQube versions? In my sonarQube 7.5 i get this ClassNotFound exception on startup:
`java.lang.IllegalStateException: Fail to load plugin Build Breaker [buildbreaker]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/CheckProject
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at org.sonar.plugins.buildbreaker.BuildBreakerPlugin.getExtensions(BuildBreakerPlugin.java:56)
	at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.CheckProject
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 25 common frames omitted`

Or is there any workaround for this exception?

**Comment by anezhinskiy** [comment]
+1 to this issue!

**Comment by rubensgomes** [comment]
Same problem on SonarQube 7.7.  Can anyone respond whether this is being fixed?

**Comment by SSANSH** [comment]
+1 on SonarQube 7.7

**Comment by vanditamathur** [comment]
+1

**Comment by timmalich** [comment]
For everyone else ending up here digging for soultions:
Found it on another link:
Some amazing super dude forked and fixed it. Works like a charm!

https://github.com/adnovum/sonar-build-breaker

**Comment by sandro-h** [comment]
Hey all, we now have a [2.3.0 release](https://github.com/adnovum/sonar-build-breaker/releases/tag/2.3.0) which supports SonarQube 7.3 - 7.9.
