### ISSUE TITLE
When I use the BuildBreaker plug-in, I want to make the build fail when the requirements are not set through the Quality Gate, but when the setting of the Quality Gate is met, the error in the Jenkins build is as follows

### ISSUE THREAD

**Issue by debuggerhu** [adnovum/sonar-build-breaker#61]
When I use the BuildBreaker plug-in, I want to make the build fail when the requirements are not set through the quality gate, but when the setting of the quality gate is met, the error in the Jenkins build is as follows

ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Fail to request https://192.168.1.213/api/ce/task?id=AXSgCm12UKz6R0ZFtZdf
...
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
...
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
...
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
...
ERROR: SonarQube scanner exited with non-zero code: 1

The following is the version I used for sonarqube
- SonarQube server version: Community Edition-8.4.2(build 36762)
- sonar-build-breaker plugin version: 2.3.1 (build 347)
- Java version used for the Sonar analysis: openJDK11
- Build context: manual execution / CI tool :Jenkins

The full logs as follows

15:08:08.370 INFO: CPD Executor CPD calculation finished (done) | time=45ms
15:08:08.379 DEBUG: SCM revision ID '04c3f5a218283b13b22d475f8e0c6f68c95a6436'
15:08:08.489 INFO: Analysis report generated in 104ms, dir size=352 KB
15:08:08.829 INFO: Analysis report compressed in 340ms, zip size=227 KB
15:08:08.829 INFO: Analysis report generated in /data/jenkins/workspace/XXX/.scannerwork/scanner-report
15:08:08.829 DEBUG: Upload report
15:08:09.031 DEBUG: POST 200 http://192.168.1.213:9000/api/ce/submit?projectKey=xxx&projectName=xxx | time=200ms
15:08:09.033 INFO: Analysis report uploaded in 204ms
15:08:09.035 DEBUG: Report metadata written to /data/jenkins/workspace/cloudpacs-preposed-Test/.scannerwork/report-task.txt
15:08:09.035 INFO: ANALYSIS SUCCESSFUL, you can browse https://192.168.1.213/dashboard?id=xxx
15:08:09.035 INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
15:08:09.035 INFO: More about the report processing at https://192.168.1.213/api/ce/task?id=AXSgCm12UKz6R0ZFtZdf
15:08:09.040 DEBUG: Post-jobs : Forbidden Configuration Breaker -> Quality Gate Breaker
15:08:09.040 INFO: Executing post-job 'Forbidden Configuration Breaker'
15:08:09.040 INFO: Executing post-job 'Quality Gate Breaker'
15:08:09.041 DEBUG: Loading report task properties from /data/jenkins/workspace/xxx/.scannerwork/report-task.txt
15:08:09.239 INFO: ------------------------------------------------------------------------
15:08:09.239 INFO: EXECUTION FAILURE
15:08:09.239 INFO: ------------------------------------------------------------------------
15:08:09.240 INFO: Total time: 11.516s
15:08:09.293 INFO: Final Memory: 12M/50M
15:08:09.293 INFO: ------------------------------------------------------------------------
15:08:09.293 ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Fail to request https://192.168.1.213/api/ce/task?id=AXSgCm12UKz6R0ZFtZdf
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:190)
	at org.sonarqube.ws.client.HttpConnector.get(HttpConnector.java:124)
	at org.sonarqube.ws.client.HttpConnector.call(HttpConnector.java:111)
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.getAnalysisId(QualityGateBreaker.java:188)
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.execute(QualityGateBreaker.java:266)
	at org.sonar.scanner.postjob.PostJobWrapper.execute(PostJobWrapper.java:49)
	at org.sonar.scanner.postjob.PostJobsExecutor.execute(PostJobsExecutor.java:48)
	at org.sonar.scanner.postjob.PostJobsExecutor.execute(PostJobsExecutor.java:39)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:368)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:268)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:238)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:188)
	... 27 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 58 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	... 64 more
ERROR: SonarQube scanner exited with non-zero code: 1
Finished: FAILURE

**Comment by sandro-h** [comment]
Hi @debuggerhu,

This looks like a standard certificate issue that I'm not sure can be solved on the build-breaker side. Is your SonarQube server using a self-signed HTTPS certificate?

One thing I'm curious about: the Scanner itself seems to make calls to **http**, not **https**:
> 15:08:09.031 DEBUG: POST 200 http://192.168.1.213:9000/api/ce/submit?projectKey=xxx&projectName=xxx | time=200ms

But the build breaker tries to call **https**:
> Fail to request https://192.168.1.213/api/ce/task?id=AXSgCm12UKz6R0ZFtZdf

Are you setting the SonarQube server's `serverUrl` to **https**? In that case an easy fix would be to configure the `sonar.buildbreaker.alternativeServerUrl` to also use the **http** URL, like the Scanner.

**Comment by debuggerhu** [comment]
> 嗨@debuggerhu，
> 
> 这看起来像是标准证书问题，我不确定能否在构建破坏者方面解决。您的SonarQube服务器是否使用自签名HTTPS证书？
> 
> 我很好奇的一件事：扫描仪本身似乎是调用**http**，而不是**https**：
> 
> > 15：08：09.031调试：POST 200 http://192.168.1.213:9000/api/ce/submit?projectKey=xxx&projectName=xxx | 时间= 200ms
> 
> 但是构建破坏者尝试调用**https**：
> 
> > 无法请求https://192.168.1.213/api/ce/task?id=AXSgCm12UKz6R0ZFtZdf
> 
> 您是否将SonarQube服务器的服务器设置`serverUrl`为**https**？在这种情况下，一个简单的解决方法是将进行配置，`sonar.buildbreaker.alternativeServerUrl`使其也使用**http** URL，例如Scanner。

I use the sonarqube default serverUrl is indeed the address of http, but because I need to use the authorization of GitLab to log in to sonarqube, and the oauth of GitLab must use https, so I use Nginx to forward and do a self-signed certificate in nginx, so when using BuilderBreaker in sonarqube, Scanner has this error message (the status of the quality gate is passed will also appear this error message), I have also tried to set serverUrl to http. BuilderBreaker can be used normally and will not report this error. I am not sure whether this error report is sonarqube or SonarScanner requires a self-signed certificate. Secondly, I would like to know this request 1514 0815 09.293 ERROR: Error during SonarScanner execution.
What is the role of java.lang.IllegalStateException: Fail to request https://192.168.1.213/api/ce/task?id=AXSgCm12UKz6R0ZFtZdf? that's what I want to know.

**Comment by debuggerhu** [comment]
thanks @sandro-h 
I use the sonarqube default serverUrl is indeed the address of http, but because I need to use the authorization of GitLab to log in to sonarqube, and the oauth of GitLab must use https, so I use Nginx to forward and do a self-signed certificate in nginx, so when using BuilderBreaker in sonarqube, Scanner has this error message (the status of the quality gate is passed will also appear this error message), I have also tried to set serverUrl to http. BuilderBreaker can be used normally and will not report this error. I am not sure whether this error report is sonarqube or SonarScanner requires a self-signed certificate. Secondly, I would like to know this request
 1514 0815 09.293 ERROR: Error during SonarScanner execution.What is the role of "java.lang.IllegalStateException: Fail to request https://192.168.1.213/api/ce/task?id=AXSgCm12UKz6R0ZFtZdf? 

that's what I want to know.

Look forward to your reply.

**Comment by debuggerhu** [comment]
I clicked on this request https://192.168.1.213/api/ce/task?id=AXSgCm12UKz6R0ZFtZdf?, on my local computer and got the following information
{
    "task": {
        "id": "AXSuJA4-oemQF1hiIRTx",
        "type": "REPORT",
        "componentId": "AXSLP2Gz9hlFi8MXNY0v",
        "componentKey": "xxx,
        "componentName": "xxx",
        "componentQualifier": "TRK",
        "analysisId": "AXSuJBBYHYn8Ugzbvc3f",
        "status": "SUCCESS",
        "submittedAt": "2020-09-21T00:50:32+0000",
        "submitterLogin": "Jenkins",
        "startedAt": "2020-09-21T00:50:32+0000",
        "executedAt": "2020-09-21T00:50:37+0000",
        "executionTimeMs": 4153,
        "logs": false,
        "hasScannerContext": true,
        "organization": "default-organization",
        "warningCount": 2,
        "warnings": []
    }
}


----------------------------------------------
What I am curious about is that although there is an error message, the web dashboard of sonarqube can see the results after this scan, so I am hungry and confused about the role of this request.

**Comment by sandro-h** [comment]
Hi @sandro-h, the build-breaker makes this request (repeatedly) to wait for the analysis to be processed by the SonarQube server. Once the server has processed the analysis, the build-breaker will request the Quality Gate status from the server and break the build depending on that status.

Regarding the self-signed certificate: the build-breaker uses the client provided by the SonarScanner. So I would except that a certificate needs to be added there. I see the following options
- Somehow configure the SonarScanner to trust your self-signed certificate. I'm doubtful they provide a way to do that.
- Add your self-signed certificate to the Java `cacerts` in your Jenkins nodes. If the SonarScanner is executed with that Java version, it should work.
- Configure `sonar.buildbreaker.alternativeServerUrl` to use `http` like mentioned before. If the build-breaker runs into authentication issues this way, you should create a Sonar authentication token (in the SonarQube UI) and pass it to the sonar analysis with `-Dsonar.login=<token>`.

**Comment by debuggerhu** [comment]
@sandro-h thanks for your reply

I don't know what value the sonar.buildbreaker.alternativeServerUrl attribute in the Build Breaker module of sonarqube should fill in, or what this url is used for. I checked the official explanation, 

 https://github.com/sandro-h/sonar-build-breaker---------------->;URL to use for web service requests. If unset, uses the serverUrl property from ${sonar.working.directory}/report-task.txt.

but I still don't know what it is used for. I hope I can get an easy-to-understand answer. Thank you.

**Comment by debuggerhu** [comment]
Hi @sandro-h 

I trusted https's certificate for sonarScanner in your way, but there was a new error. The log message is as follows

17:33:40.013 ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Fail to request https://192.168.1.213/api/ce/task?id=AXSwAplCoemQF1hiIRUL
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:190)
	at org.sonarqube.ws.client.HttpConnector.get(HttpConnector.java:124)
	at org.sonarqube.ws.client.HttpConnector.call(HttpConnector.java:111)
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.getAnalysisId(QualityGateBreaker.java:188)
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.execute(QualityGateBreaker.java:266)
	at org.sonar.scanner.postjob.PostJobWrapper.execute(PostJobWrapper.java:49)
	at org.sonar.scanner.postjob.PostJobsExecutor.execute(PostJobsExecutor.java:48)
	at org.sonar.scanner.postjob.PostJobsExecutor.execute(PostJobsExecutor.java:39)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:368)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname 192.168.1.213 not verified:
    certificate: sha256/56af+1yHs8Oppo8jmxCSWQKu13N/ZPa+TmoL+SneVDw=
    DN: EMAILADDRESS=123@wisonic.com, CN=192.168.1.213, OU=wisonic, O=wisonic, L=shenzhen, ST=guangdong, C=CN
    subjectAltNames: []
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:277)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:238)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:188)
	... 27 more
ERROR: SonarQube scanner exited with non-zero code: 1
Finished: FAILURE

**Comment by sandro-h** [comment]
Hi @debuggerhu, it looks like your certificate is still not completely correct. Bit tricky for me to find out what's missing. Potentially the host name (ip address) should also be listed in the subjectAltNames of the certificate.

> I don't know what value the sonar.buildbreaker.alternativeServerUrl attribute in the Build Breaker module of sonarqube should fill in, or what this url is used for

In your case, I think the value should be `http://192.168.1.213:9000`.

**Comment by debuggerhu** [comment]
@sandro-h @ehartmann @Godin @dgageot 
Dear developers of BuilderBreaker

Through the above error log, I found that BuilderBreaker is communicating with sonar and Scanner, so I want to know how BuilderBreaker causes the construction of Jenkins to fail, and how to obtain the quality gate. My guess is: Jenkins triggers Scanner to scan, and Scanner gets the scanning rules from the sonarqube server (which includes the configuration of BuilderBreaker,), Scanner, and then sends the scan results to the Sonarqube server. There are several transmission processes in the process. 
I want to know the entry point between how BuilderBreaker works and Jenkins and Sonarqube,Scanner. I hope to get a code-level explanation. Thank you.

**Comment by debuggerhu** [comment]
hi @sandro-h 

I used BuilderBreaker, and did not open Skip quality gate check, and set the quality gate to a condition that the test project would not pass. For example, the odor number of my project was 500, and I set the odor limit of 300 to create a test case that failed the quality gate. 
However, the SonarScanner scan, the analysis was successful, but the execution failed. I see a log line like this: 
Post-jobs: Forbidden Configuration Breaker-> Quality Gate Breaker. 
These two Post-jobs: 
INFO: Executing post-job 'Forbidden Configuration Breaker' 
INFO: Executing post-job 'Quality Gate Breaker' 
Are the above two post-job executed by Scanner, because I see below. 
ERROR: Error during SonarScanner execution. 
Therefore, after getting the compiled bytecode file, Scanner obtains the scanning rules, quality threshold and other configuration files from Sonarqube to Scanner locally, and then performs the analysis. If the post-jod, fails to pass, it will cause Scanner execution to fail. 
Although the execution of Scanner failed, it was a failure of post-jod, and the previous analysis was successful, right? 
But I tested another situation. 
I set the limit of the odor to be greater than the number of odors of the actual project, and use Jenkins to build again, and the result is still the same error message as above, but the green display is normal on the project dashboard of sonarqube. 
This makes me very confused. I hope I can get an answer. Thank you.


The execution log is as follows:
......
 Analysis report uploaded in 108ms
INFO: ANALYSIS SUCCESSFUL, you can browse https://192.168.1.213/dashboard?id=wisonic-cloudpacs-preposed
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at https://192.168.1.213/api/ce/task?id=AXVOGSRW6jeqfX_nGjiq
INFO: Executing post-job 'Forbidden Configuration Breaker'
INFO: Executing post-job 'Quality Gate Breaker'
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 12.438s
INFO: Final Memory: 12M/50M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Fail to request https://192.168.1.213/api/ce/task?id=AXVOGSRW6jeqfX_nGjiq
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:190)
	at org.sonarqube.ws.client.HttpConnector.get(HttpConnector.java:124)
	at org.sonarqube.ws.client.HttpConnector.call(HttpConnector.java:111)
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.getAnalysisId(QualityGateBreaker.java:188)
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.execute(QualityGateBreaker.java:266)
	at org.sonar.scanner.postjob.PostJobWrapper.execute(PostJobWrapper.java:49)
	at org.sonar.scanner.postjob.PostJobsExecutor.execute(PostJobsExecutor.java:48)
	at org.sonar.scanner.postjob.PostJobsExecutor.execute(PostJobsExecutor.java:39)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:368)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname 192.168.1.213 not verified:
    certificate: sha256/m3MVPuVhM4LMMOl6Wm9hSAxFUf9qeReFerfrSyWH8SY=
    DN: CN=wisonic.com, EMAILADDRESS=123@xxx.com, OU=IT Department, O=xxx, L=ShenZhen, ST=GuangDong, C=CN
    subjectAltNames: [192.168.1.213]
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:277)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:238)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:188)
	... 27 more
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
ERROR: SonarQube scanner exited with non-zero code: 1
Finished: FAILURE

**Comment by debuggerhu** [comment]
hi @sandro-h 

I went to sonarqube's server and checked the web.log and ce.log, messages under sonarqube_logs and found that they were incoming error messages.

I found that when I checked ce.log/web.log, I found that this was an error caused by a request to query the database, so I wanted to know whether the query database was ES or postgreSQL, and if it was PostgresSQL, did I need to use the connection settings of https in the configuration postgreSQLde configuration information of sonarqube?

2020.10.22 02:49:35 ERROR web[][o.s.s.p.w.RootFilter] Processing of request /dashboard?id=wisonic-cloudpacs-preposed failed
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: Connection to 192.168.1.213:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
### The error may exist in org.sonar.db.user.SessionTokenMapper
### The error may involve org.sonar.db.user.SessionTokenMapper.selectByUuid
### The error occurred while executing a query
### Cause: org.postgresql.util.PSQLException: Connection to 192.168.1.213:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
...
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: Connection to 192.168.1.213:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
...
Caused by: java.net.ConnectException: Connection refused (Connection refused)
...
2020.10.22 02:49:42 WARN  web[][o.a.c.d.BasicDataSource] An internal object pool swallowed an Exception.
org.postgresql.util.PSQLException: Connection to 192.168.1.213:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
...
Caused by: java.net.ConnectException: Connection refused (Connection refused)
...
2020.10.22 02:49:48 ERROR web[][o.s.s.p.w.RootFilter] Processing of request / failed

**Comment by sandro-h** [comment]
Hi @debuggerhu, it still looks like a problem with your server certificate.

> My guess is: Jenkins triggers Scanner to scan, and Scanner gets the scanning rules from the sonarqube server (which includes the configuration of BuilderBreaker,), Scanner, and then sends the scan results to the Sonarqube server. There are several transmission processes in the process.
I want to know the entry point between how BuilderBreaker works and Jenkins and Sonarqube,Scanner. I hope to get a code-level explanation. Thank you.

After the scanner sends the scan result to the Sonarqube server, the build breaker will poll the server for the quality gate result (this is a post-job task). It's running in the same scanner process so it trusts the same certificates as the scanner. Independent of that, if you set `sonar.buildbreaker.alternativeServerUrl` to the direct http url of the Sonarqube server, the certificate will not cause any problems. The scanner also uses the http url to communicate with the server.

**Comment by hosszubalazs** [comment]
Hey @debuggerhu ,

Please let us know if you have managed to solve your issue. Do you have any specific questions we can help with?

Cheers,
Balázs
