### ISSUE TITLE
Quality Gate Breaker crashes on SQ 8.5.1 (FYI as I'm aware you haven't listed this version on the readme)

### ISSUE THREAD

**Issue by fireflycons** [adnovum/sonar-build-breaker#63]
**Describe the bug**
When running Quality Gate Breaker, the build crashes with the following
```
build	26-Oct-2020 12:54:12	INFO: Executing post-job 'Quality Gate Breaker'
build	26-Oct-2020 12:54:13	INFO: ------------------------------------------------------------------------
build	26-Oct-2020 12:54:13	INFO: EXECUTION FAILURE
build	26-Oct-2020 12:54:13	INFO: ------------------------------------------------------------------------
build	26-Oct-2020 12:54:13	INFO: Total time: 35.199s
error	26-Oct-2020 12:54:13	ERROR: Error during SonarQube Scanner execution
error	26-Oct-2020 12:54:13	ERROR: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
error	26-Oct-2020 12:54:13	ERROR: Caused by: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
```
If I enable the `Skip quality gate check` switch in the plugin configuration, it is fine.

**Context**
At the minimum, provide the SonarQube and plugin version:

- SonarQube server version: `8.5.1`
- sonar-build-breaker plugin version: `2.3.1.354`
- Java version used for the Sonar analysis: ...
- Build context: Bamboo 6.9.1 (Windows)
```
26-Oct-2020 12:53:38 | INFO: SonarQube Scanner 3.3.0.1492
26-Oct-2020 12:53:38 | INFO: Java 1.8.0_202 AdoptOpenJdk (64-bit)
26-Oct-2020 12:53:38 | INFO: Windows Server 2016 10.0 amd64
26-Oct-2020 12:53:38 | INFO: User cache: C:\Users\Bamboo\.sonar\cache
26-Oct-2020 12:53:40 | INFO: SonarQube server 8.5.1
```

**To Reproduce**

* Run a build that was fine on our production SQ setup (8.1) on the 8.5.1 test rig.

**Expected behavior**
* For it not to crash

**Logs**
As above

**Additional context**

**Comment by fireflycons** [comment]
Further info.

It currently works with SQ 8.2 and build breaker 2.3.1.347 on the same base Bamboo agent

I've also tried the following combinations, resulting in the same error message
```
SonarQube Build Breaker
=======   =========
3.4       2.3.1.354
3.4       2.3.1.347
3.3       2.3.1.347 
```

**Comment by sandro-h** [comment]
Hi @fireflycons, I'm verifying if the plugin should still work with SonarQube 8.5 now. I'll let you know when I have some results.

Regarding your additional tries: I assume you mean SonarQube 8.4 and 8.3 (not 3.4, 3.3), right?

**Comment by fireflycons** [comment]
I do indeed, yes :-)

**Comment by sandro-h** [comment]
I could verify that the build breaker works in 8.5.1 with our verification smoke tests (using a plain SonarQube docker container and a tiny maven project).

Could you rerun your build with error stacktraces enabled? They contain useful information, especially what URL the build breaker is trying to use to get the quality gate information from the server. I've seen similar "protocol" errors when the breaker tried to use an invalid URL (for example going through a corporate proxy instead of directly to the Sonar server).

Not sure how exactly your Bamboo setup executes Sonar, for maven the stacktraces can usually be enabled with the  `-e` flag, for gradle `--stacktrace`.

**Comment by fireflycons** [comment]
In most cases it is from CakeBuild and the analysis happens in the SonarEnd task (via https://github.com/AgileArchitect/Cake.Sonar) however there is at least one project that's built with Maven on a Linux server - same result.
Will have to talk to the dev team about how that's set up tomorrow (we're UK based)

**Comment by fireflycons** [comment]
But I can verify that there's no proxies in the way.
Bamboo agents are elastic one of our AWS accounts. SonarQube is in another of our accounts.
Route is Build Server -> NAT Gateway -> Internet -> Load Balancer -> SonarQube

**Comment by fireflycons** [comment]
@sandro-h In the words of your avatar... D'OH!

What you said about the URL reminded me that I had not updated the Server Base URL after making a copy of the production database.

I ran with the verbose options on using 8.5.1 and 2.3.1.347 and got an exception (below), then updated Server Base URL and it went through. I think we are all good now.

Thanks for your help!

For reference

```
error	28-Oct-2020 10:03:49	10:03:49.817 ERROR: Error during SonarQube Scanner execution
error	28-Oct-2020 10:03:49	java.lang.IllegalStateException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
error	28-Oct-2020 10:03:49		at org.sonar.plugins.buildbreaker.QualityGateBreaker.getAnalysisId(QualityGateBreaker.java:209)
error	28-Oct-2020 10:03:49		at org.sonar.plugins.buildbreaker.QualityGateBreaker.execute(QualityGateBreaker.java:266)
error	28-Oct-2020 10:03:49		at org.sonar.scanner.postjob.PostJobWrapper.execute(PostJobWrapper.java:49)
error	28-Oct-2020 10:03:49		at org.sonar.scanner.postjob.PostJobsExecutor.execute(PostJobsExecutor.java:48)
error	28-Oct-2020 10:03:49		at org.sonar.scanner.postjob.PostJobsExecutor.execute(PostJobsExecutor.java:39)
error	28-Oct-2020 10:03:49		at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:373)
error	28-Oct-2020 10:03:49		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
error	28-Oct-2020 10:03:49		at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
error	28-Oct-2020 10:03:49		at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
error	28-Oct-2020 10:03:49		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
error	28-Oct-2020 10:03:49		at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
error	28-Oct-2020 10:03:49		at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
error	28-Oct-2020 10:03:49		at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
error	28-Oct-2020 10:03:49		at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
error	28-Oct-2020 10:03:49		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
error	28-Oct-2020 10:03:49		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
error	28-Oct-2020 10:03:49		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
error	28-Oct-2020 10:03:49		at java.lang.reflect.Method.invoke(Method.java:498)
error	28-Oct-2020 10:03:49		at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
error	28-Oct-2020 10:03:49		at com.sun.proxy.$Proxy0.execute(Unknown Source)
error	28-Oct-2020 10:03:49		at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
error	28-Oct-2020 10:03:49		at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
error	28-Oct-2020 10:03:49		at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
error	28-Oct-2020 10:03:49		at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
error	28-Oct-2020 10:03:49		at org.sonarsource.scanner.cli.Main.main(Main.java:61)
error	28-Oct-2020 10:03:49	Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
error	28-Oct-2020 10:03:49		at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:86)
error	28-Oct-2020 10:03:49		at com.google.protobuf.CodedInputStream$StreamDecoder.readRawBytesSlowPathOneChunk(CodedInputStream.java:2944)
error	28-Oct-2020 10:03:49		at com.google.protobuf.CodedInputStream$StreamDecoder.readBytesSlowPath(CodedInputStream.java:2991)
error	28-Oct-2020 10:03:49		at com.google.protobuf.CodedInputStream$StreamDecoder.readBytes(CodedInputStream.java:2419)
error	28-Oct-2020 10:03:49		at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:537)
error	28-Oct-2020 10:03:49		at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:514)
error	28-Oct-2020 10:03:49		at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:633)
error	28-Oct-2020 10:03:49		at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:295)
error	28-Oct-2020 10:03:49		at com.google.protobuf.CodedInputStream$StreamDecoder.readGroup(CodedInputStream.java:2344)
error	28-Oct-2020 10:03:49		at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:541)
error	28-Oct-2020 10:03:49		at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:293)
error	28-Oct-2020 10:03:49		at org.sonarqube.ws.Ce$TaskResponse.<init>(Ce.java:1025)
error	28-Oct-2020 10:03:49		at org.sonarqube.ws.Ce$TaskResponse.<init>(Ce.java:988)
error	28-Oct-2020 10:03:49		at org.sonarqube.ws.Ce$TaskResponse$1.parsePartialFrom(Ce.java:1545)
error	28-Oct-2020 10:03:49		at org.sonarqube.ws.Ce$TaskResponse$1.parsePartialFrom(Ce.java:1540)
error	28-Oct-2020 10:03:49		at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:221)
error	28-Oct-2020 10:03:49		at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:239)
error	28-Oct-2020 10:03:49		at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:244)
error	28-Oct-2020 10:03:49		at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
error	28-Oct-2020 10:03:49		at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:311)
error	28-Oct-2020 10:03:49		at org.sonarqube.ws.Ce$TaskResponse.parseFrom(Ce.java:1193)
error	28-Oct-2020 10:03:49		at org.sonar.plugins.buildbreaker.QualityGateBreaker.getAnalysisId(QualityGateBreaker.java:191)
error	28-Oct-2020 10:03:49		... 24 more
build	28-Oct-2020 10:03:49	10:03:49.817 INFO: Final Memory: 36M/360M
```

**Comment by fireflycons** [comment]
I'll close this now

Cheers.

**Comment by sandro-h** [comment]
> In the words of your avatar... D'OH!

😄 Glad to hear you managed to fix it. As a side-effect, we've verified it works for 8.5 now. I'll update our tests and compatibility table tomorrow.
